"""stage5b reconciliation data model

Revision ID: 0e4526e93f67
Revises: 8be992965c74
Create Date: 2026-09-24 16:16:52.048307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0e4526e93f67'
down_revision: Union[str, None] = '8be992965c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: autogenerate proposed dropping/recreating several hand-written
    # partial unique indexes it doesn't reflect in SQLAlchemy model
    # metadata (from Stage 3/4/5A) - those lines were removed
    # deliberately; none of them are touched by this migration.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_configurations',
    sa.Column('legal_entity_id', sa.UUID(), nullable=True),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('amount_tolerance_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('date_tolerance_days', sa.Integer(), nullable=False),
    sa.Column('high_value_threshold', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('duplicate_policy', sa.String(length=50), nullable=True),
    sa.Column('matching_rule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['reconciliation_configurations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_entity_id', 'bank_account_id', 'currency_code', 'version', name='uq_reconciliation_configuration_identity')
    )
    op.create_index(op.f('ix_reconciliation_configurations_bank_account_id'), 'reconciliation_configurations', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_configurations_is_current'), 'reconciliation_configurations', ['is_current'], unique=False)
    op.create_index(op.f('ix_reconciliation_configurations_legal_entity_id'), 'reconciliation_configurations', ['legal_entity_id'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='reconciliationrunstatus'), nullable=False),
    sa.Column('configuration_id', sa.UUID(), nullable=True),
    sa.Column('statement_transaction_count', sa.Integer(), nullable=False),
    sa.Column('eligible_transaction_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('executed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['configuration_id'], ['reconciliation_configurations.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_bank_account_id'), 'reconciliation_runs', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_legal_entity_id'), 'reconciliation_runs', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_status'), 'reconciliation_runs', ['status'], unique=False)
    op.create_table('reconciliation_match_suggestions',
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('bank_statement_transaction_id', sa.UUID(), nullable=True),
    sa.Column('treasury_transaction_id', sa.UUID(), nullable=True),
    sa.Column('match_type', sa.Enum('ONE_TO_ONE', 'ONE_TO_MANY', 'MANY_TO_ONE', 'BATCH_PAYMENT', 'INTERNAL_TRANSFER', 'BANK_CHARGE', 'FX_ADJUSTED', 'OTHER', name='matchtype'), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'SUPERSEDED', name='matchsuggestionstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('matching_rule_version', sa.String(length=50), nullable=True),
    sa.Column('weights_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_statement_transaction_id'], ['bank_statement_transactions.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ),
    sa.ForeignKeyConstraint(['treasury_transaction_id'], ['treasury_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_match_suggestions_bank_statement_transaction_id'), 'reconciliation_match_suggestions', ['bank_statement_transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_suggestions_reconciliation_run_id'), 'reconciliation_match_suggestions', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_suggestions_status'), 'reconciliation_match_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_suggestions_treasury_transaction_id'), 'reconciliation_match_suggestions', ['treasury_transaction_id'], unique=False)
    op.create_table('reconciliation_open_items',
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('bank_statement_transaction_id', sa.UUID(), nullable=True),
    sa.Column('treasury_transaction_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('BANK_ONLY', 'LEDGER_ONLY', 'AMOUNT_VARIANCE', 'TIMING_DIFFERENCE', 'DUPLICATE', 'BANK_CHARGE', 'INTERNAL_TRANSFER', 'FX_DIFFERENCE', 'ONE_TO_MANY', 'MANY_TO_ONE', 'BATCH_PAYMENT', 'MISSING_LEDGER_ENTRY', 'MISSING_BANK_ENTRY', 'EXCEPTION', name='openitemcategory'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'CLOSED', 'REJECTED', name='openitemstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['bank_statement_transaction_id'], ['bank_statement_transactions.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ),
    sa.ForeignKeyConstraint(['treasury_transaction_id'], ['treasury_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_open_items_assigned_to_user_id'), 'reconciliation_open_items', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_open_items_bank_account_id'), 'reconciliation_open_items', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_open_items_bank_statement_transaction_id'), 'reconciliation_open_items', ['bank_statement_transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_open_items_category'), 'reconciliation_open_items', ['category'], unique=False)
    op.create_index(op.f('ix_reconciliation_open_items_legal_entity_id'), 'reconciliation_open_items', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_open_items_reconciliation_run_id'), 'reconciliation_open_items', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_open_items_status'), 'reconciliation_open_items', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_open_items_treasury_transaction_id'), 'reconciliation_open_items', ['treasury_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_open_items_treasury_transaction_id'), table_name='reconciliation_open_items')
    op.drop_index(op.f('ix_reconciliation_open_items_status'), table_name='reconciliation_open_items')
    op.drop_index(op.f('ix_reconciliation_open_items_reconciliation_run_id'), table_name='reconciliation_open_items')
    op.drop_index(op.f('ix_reconciliation_open_items_legal_entity_id'), table_name='reconciliation_open_items')
    op.drop_index(op.f('ix_reconciliation_open_items_category'), table_name='reconciliation_open_items')
    op.drop_index(op.f('ix_reconciliation_open_items_bank_statement_transaction_id'), table_name='reconciliation_open_items')
    op.drop_index(op.f('ix_reconciliation_open_items_bank_account_id'), table_name='reconciliation_open_items')
    op.drop_index(op.f('ix_reconciliation_open_items_assigned_to_user_id'), table_name='reconciliation_open_items')
    op.drop_table('reconciliation_open_items')
    op.drop_index(op.f('ix_reconciliation_match_suggestions_treasury_transaction_id'), table_name='reconciliation_match_suggestions')
    op.drop_index(op.f('ix_reconciliation_match_suggestions_status'), table_name='reconciliation_match_suggestions')
    op.drop_index(op.f('ix_reconciliation_match_suggestions_reconciliation_run_id'), table_name='reconciliation_match_suggestions')
    op.drop_index(op.f('ix_reconciliation_match_suggestions_bank_statement_transaction_id'), table_name='reconciliation_match_suggestions')
    op.drop_table('reconciliation_match_suggestions')
    op.drop_index(op.f('ix_reconciliation_runs_status'), table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_legal_entity_id'), table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_bank_account_id'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_configurations_legal_entity_id'), table_name='reconciliation_configurations')
    op.drop_index(op.f('ix_reconciliation_configurations_is_current'), table_name='reconciliation_configurations')
    op.drop_index(op.f('ix_reconciliation_configurations_bank_account_id'), table_name='reconciliation_configurations')
    op.drop_table('reconciliation_configurations')
    # ### end Alembic commands ###
