"""add investment transaction cash ledger linkage

Revision ID: 146d9a612050
Revises: 571ec4b77c92
Create Date: 2026-09-21 15:56:49.774234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '146d9a612050'
down_revision: Union[str, None] = '571ec4b77c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: autogenerate proposed dropping/recreating
    # ux_funding_actions_linked_drawdown_id / ux_funding_actions_linked_repayment_id
    # here (Stage 3 hand-written partial unique indexes SQLAlchemy's model
    # metadata doesn't reflect) - removed from both upgrade() and
    # downgrade() deliberately; those indexes are untouched.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_transactions', sa.Column('cash_transaction_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_investment_transactions_cash_transaction_id'), 'investment_transactions', ['cash_transaction_id'], unique=False)
    op.create_foreign_key(None, 'investment_transactions', 'treasury_transactions', ['cash_transaction_id'], ['id'])
    # ### end Alembic commands ###

    # SECTION 15/16: defense in depth (same pattern as Stage 3's
    # funding_actions partial unique indexes) - at the database level,
    # not just application-level row locking, a given investment may
    # have at most one PLACEMENT transaction. A concurrent second
    # placement INSERT is rejected by Postgres itself even if it somehow
    # bypassed the row lock.
    op.execute(
        "CREATE UNIQUE INDEX ux_investment_transactions_one_placement "
        "ON investment_transactions (investment_id) "
        "WHERE transaction_type = 'PLACEMENT'"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ux_investment_transactions_one_placement")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investment_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_investment_transactions_cash_transaction_id'), table_name='investment_transactions')
    op.drop_column('investment_transactions', 'cash_transaction_id')
    # ### end Alembic commands ###
