"""add forecast opening cash snapshot

Revision ID: 15f25d80fddd
Revises: a1b9ea9bea9e
Create Date: 2026-09-16 05:44:41.295335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '15f25d80fddd'
down_revision: Union[str, None] = 'a1b9ea9bea9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('opening_cash_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Traceable opening cash used for week 1, keyed 'entity_id|currency_code' -> amount, captured from the Cash Position service at calculation time."))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecasts', 'opening_cash_snapshot')
    # ### end Alembic commands ###
