"""stage5a bank statement transactions

Revision ID: 8be992965c74
Revises: 048a6772faf5
Create Date: 2026-09-24 09:24:24.907061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8be992965c74'
down_revision: Union[str, None] = '048a6772faf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_statement_transactions',
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('statement_period_start', sa.Date(), nullable=False),
    sa.Column('statement_period_end', sa.Date(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('entry_type', sa.Enum('DEBIT', 'CREDIT', name='bankstatemententrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('balance_after_transaction', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('bank_reference', sa.String(length=150), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=150), nullable=True),
    sa.Column('narration', sa.String(length=500), nullable=True),
    sa.Column('duplicate_key', sa.String(length=128), nullable=False),
    sa.Column('has_strong_identity', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVERSED', name='bankstatementtransactionstatus'), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statement_transactions_bank_account_id'), 'bank_statement_transactions', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_bank_id'), 'bank_statement_transactions', ['bank_id'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_bank_reference'), 'bank_statement_transactions', ['bank_reference'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_currency_code'), 'bank_statement_transactions', ['currency_code'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_duplicate_key'), 'bank_statement_transactions', ['duplicate_key'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_external_transaction_id'), 'bank_statement_transactions', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_import_batch_id'), 'bank_statement_transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_legal_entity_id'), 'bank_statement_transactions', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_status'), 'bank_statement_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_transaction_date'), 'bank_statement_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_value_date'), 'bank_statement_transactions', ['value_date'], unique=False)
    # NOTE: autogenerate proposed dropping/recreating several hand-written
    # partial unique indexes it doesn't reflect in SQLAlchemy model
    # metadata (Stage 3/4 indexes) - those lines were removed
    # deliberately; none of them are touched by this migration.
    # ### end Alembic commands ###

    # SECTION 11/12 (Stage 5A): a row with strong identity evidence (a
    # bank reference or external transaction id) can never be durably
    # persisted twice with the same duplicate_key - database-level
    # defense in depth behind the application-level exact-duplicate
    # check in bank_statement_excel_template.py. Rows with ONLY weak
    # identity (has_strong_identity = false) are deliberately NOT
    # covered - two such rows are at most POTENTIAL_DUPLICATE and both
    # are still imported, so the database must not reject them.
    op.execute(
        "CREATE UNIQUE INDEX ux_bank_statement_transactions_strong_duplicate_key "
        "ON bank_statement_transactions (duplicate_key) "
        "WHERE has_strong_identity = true"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ux_bank_statement_transactions_strong_duplicate_key")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_statement_transactions_value_date'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statement_transactions_transaction_date'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statement_transactions_status'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statement_transactions_legal_entity_id'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statement_transactions_import_batch_id'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statement_transactions_external_transaction_id'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statement_transactions_duplicate_key'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statement_transactions_currency_code'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statement_transactions_bank_reference'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statement_transactions_bank_id'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statement_transactions_bank_account_id'), table_name='bank_statement_transactions')
    op.drop_table('bank_statement_transactions')
    # ### end Alembic commands ###
