"""stage3 forecast engine

Revision ID: a1b9ea9bea9e
Revises: 911663feec49
Create Date: 2026-09-16 05:43:06.699105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a1b9ea9bea9e'
down_revision: Union[str, None] = '911663feec49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_categories',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', postgresql.ENUM('INFLOW', 'OUTFLOW', 'TRANSFER', 'NON_CASH', name='cashdirection', create_type=False), nullable=False),
    sa.Column('parent_code', sa.String(length=50), nullable=True),
    sa.Column('forecastable', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_code'], ['forecast_categories.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('forecasts',
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('legal_entity_id', sa.UUID(), nullable=True),
    sa.Column('forecast_start_date', sa.Date(), nullable=False),
    sa.Column('forecast_end_date', sa.Date(), nullable=False),
    sa.Column('scenario', sa.Enum('BASE', 'CONSERVATIVE', 'STRESS', name='forecastscenariotype'), nullable=False),
    sa.Column('value_basis', sa.Enum('GROSS', 'PROBABILITY_ADJUSTED', name='forecastvaluebasis'), nullable=False),
    sa.Column('reporting_currency_code', sa.String(length=3), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_forecast_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='forecaststatus'), nullable=False),
    sa.Column('assumptions_notes', sa.String(length=2000), nullable=True),
    sa.Column('data_quality_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('published_by_user_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['parent_forecast_id'], ['forecasts.id'], ),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporting_currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_group_id'), 'forecasts', ['group_id'], unique=False)
    op.create_index(op.f('ix_forecasts_legal_entity_id'), 'forecasts', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_forecasts_scenario'), 'forecasts', ['scenario'], unique=False)
    op.create_index(op.f('ix_forecasts_status'), 'forecasts', ['status'], unique=False)
    op.create_table('recurring_cash_flows',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('direction', postgresql.ENUM('INFLOW', 'OUTFLOW', 'TRANSFER', 'NON_CASH', name='cashdirection', create_type=False), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'CUSTOM', name='recurringfrequency'), nullable=False),
    sa.Column('custom_interval_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_code'], ['forecast_categories.code'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_cash_flows_legal_entity_id'), 'recurring_cash_flows', ['legal_entity_id'], unique=False)
    op.create_table('forecast_adjustments',
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('direction', postgresql.ENUM('INFLOW', 'OUTFLOW', 'TRANSFER', 'NON_CASH', name='cashdirection', create_type=False), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'APPLIED', name='adjustmentstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_code'], ['forecast_categories.code'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_adjustments_forecast_id'), 'forecast_adjustments', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_forecast_adjustments_legal_entity_id'), 'forecast_adjustments', ['legal_entity_id'], unique=False)
    op.create_table('forecast_alerts',
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='alertstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_alerts_forecast_id'), 'forecast_alerts', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_forecast_alerts_severity'), 'forecast_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_forecast_alerts_status'), 'forecast_alerts', ['status'], unique=False)
    op.create_table('forecast_scenario_assumptions',
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('assumption_type', sa.String(length=100), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('category_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['forecast_categories.code'], ),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_scenario_assumptions_forecast_id'), 'forecast_scenario_assumptions', ['forecast_id'], unique=False)
    op.create_table('forecast_weeks',
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('FUTURE', 'CURRENT', 'COMPLETED', name='weekstatus'), nullable=False),
    sa.Column('opening_cash', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_inflows', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_outflows', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('net_transfers', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('net_cash_flow', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('closing_cash', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('minimum_required_liquidity', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('surplus_or_gap', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('liquidity_available', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('liquidity_required', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('liquidity_coverage_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_weeks_forecast_id'), 'forecast_weeks', ['forecast_id'], unique=False)
    op.create_table('liquidity_thresholds',
    sa.Column('scope_type', sa.Enum('GROUP', 'ENTITY', 'CURRENCY', 'BANK_ACCOUNT', name='liquidityscopetype'), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('minimum_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidity_thresholds_currency_code'), 'liquidity_thresholds', ['currency_code'], unique=False)
    op.create_index(op.f('ix_liquidity_thresholds_legal_entity_id'), 'liquidity_thresholds', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_liquidity_thresholds_scope_type'), 'liquidity_thresholds', ['scope_type'], unique=False)
    op.create_table('forecast_lines',
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('week_id', sa.UUID(), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('direction', postgresql.ENUM('INFLOW', 'OUTFLOW', 'TRANSFER', 'NON_CASH', name='cashdirection', create_type=False), nullable=False),
    sa.Column('transaction_currency_code', sa.String(length=3), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('adjusted_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment="original_amount after the forecast's value_basis"),
    sa.Column('reporting_currency_code', sa.String(length=3), nullable=False),
    sa.Column('reporting_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('fx_rate_type', sa.String(length=20), nullable=True),
    sa.Column('fx_rate_date', sa.Date(), nullable=True),
    sa.Column('source_type', sa.Enum('ACTUAL', 'EXPECTED_COLLECTION', 'EXPECTED_PAYMENT', 'RECURRING', 'MANUAL_ADJUSTMENT', 'SCENARIO_ADJUSTMENT', 'FUTURE_LOAN', 'FUTURE_INVESTMENT', 'FUTURE_INTERCOMPANY', 'OTHER', name='forecastsourcetype'), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['forecast_categories.code'], ),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['transaction_currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['week_id'], ['forecast_weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_lines_category_code'), 'forecast_lines', ['category_code'], unique=False)
    op.create_index(op.f('ix_forecast_lines_forecast_id'), 'forecast_lines', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_forecast_lines_legal_entity_id'), 'forecast_lines', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_forecast_lines_source_type'), 'forecast_lines', ['source_type'], unique=False)
    op.create_index(op.f('ix_forecast_lines_transaction_currency_code'), 'forecast_lines', ['transaction_currency_code'], unique=False)
    op.create_index(op.f('ix_forecast_lines_week_id'), 'forecast_lines', ['week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_lines_week_id'), table_name='forecast_lines')
    op.drop_index(op.f('ix_forecast_lines_transaction_currency_code'), table_name='forecast_lines')
    op.drop_index(op.f('ix_forecast_lines_source_type'), table_name='forecast_lines')
    op.drop_index(op.f('ix_forecast_lines_legal_entity_id'), table_name='forecast_lines')
    op.drop_index(op.f('ix_forecast_lines_forecast_id'), table_name='forecast_lines')
    op.drop_index(op.f('ix_forecast_lines_category_code'), table_name='forecast_lines')
    op.drop_table('forecast_lines')
    op.drop_index(op.f('ix_liquidity_thresholds_scope_type'), table_name='liquidity_thresholds')
    op.drop_index(op.f('ix_liquidity_thresholds_legal_entity_id'), table_name='liquidity_thresholds')
    op.drop_index(op.f('ix_liquidity_thresholds_currency_code'), table_name='liquidity_thresholds')
    op.drop_table('liquidity_thresholds')
    op.drop_index(op.f('ix_forecast_weeks_forecast_id'), table_name='forecast_weeks')
    op.drop_table('forecast_weeks')
    op.drop_index(op.f('ix_forecast_scenario_assumptions_forecast_id'), table_name='forecast_scenario_assumptions')
    op.drop_table('forecast_scenario_assumptions')
    op.drop_index(op.f('ix_forecast_alerts_status'), table_name='forecast_alerts')
    op.drop_index(op.f('ix_forecast_alerts_severity'), table_name='forecast_alerts')
    op.drop_index(op.f('ix_forecast_alerts_forecast_id'), table_name='forecast_alerts')
    op.drop_table('forecast_alerts')
    op.drop_index(op.f('ix_forecast_adjustments_legal_entity_id'), table_name='forecast_adjustments')
    op.drop_index(op.f('ix_forecast_adjustments_forecast_id'), table_name='forecast_adjustments')
    op.drop_table('forecast_adjustments')
    op.drop_index(op.f('ix_recurring_cash_flows_legal_entity_id'), table_name='recurring_cash_flows')
    op.drop_table('recurring_cash_flows')
    op.drop_index(op.f('ix_forecasts_status'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_scenario'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_legal_entity_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_group_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_table('forecast_categories')
    # ### end Alembic commands ###
