"""stage3 funding and credit facilities

Revision ID: b12c99fb6682
Revises: a212612a246f
Create Date: 2026-09-17 04:58:20.659449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b12c99fb6682'
down_revision: Union[str, None] = 'a212612a246f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Stage 3 addition: extend the existing forecastsourcetype enum with
    # facility-driven source types, so ForecastLine can trace amounts back
    # to a FacilityRepayment/FacilityDrawdown/interest/fee without a second
    # source-type system. ADD VALUE runs outside the autogenerated block
    # since Alembic's autogenerate does not detect enum value additions.
    op.execute("ALTER TYPE forecastsourcetype ADD VALUE IF NOT EXISTS 'FACILITY_DRAWDOWN'")
    op.execute("ALTER TYPE forecastsourcetype ADD VALUE IF NOT EXISTS 'FACILITY_REPAYMENT'")
    op.execute("ALTER TYPE forecastsourcetype ADD VALUE IF NOT EXISTS 'FACILITY_INTEREST'")
    op.execute("ALTER TYPE forecastsourcetype ADD VALUE IF NOT EXISTS 'FACILITY_FEE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('facilities',
    sa.Column('facility_reference', sa.String(length=100), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('facility_type_code', sa.String(length=50), nullable=False),
    sa.Column('commitment_type', sa.Enum('COMMITTED', 'UNCOMMITTED', name='commitmenttype'), nullable=False),
    sa.Column('lender_id', sa.UUID(), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('approved_limit', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('committed_limit', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('current_drawn_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('covenant_restricted_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='Amount of committed_limit made unavailable by covenant/borrowing-base restrictions - see facility_engine.calculate_utilization.'),
    sa.Column('interest_rate_type', sa.Enum('FIXED', 'VARIABLE', 'BENCHMARK_PLUS_SPREAD', 'CUSTOM', name='interestratetype'), nullable=False),
    sa.Column('benchmark_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('spread', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('fixed_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('day_count_convention', sa.Enum('ACT_365', 'ACT_360', 'THIRTY_360', name='daycountconvention'), nullable=False),
    sa.Column('arrangement_fee', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('commitment_fee_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('processing_fee', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('availability_start_date', sa.Date(), nullable=True),
    sa.Column('availability_end_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('repayment_frequency', sa.String(length=20), nullable=True),
    sa.Column('repayment_method', sa.Enum('EQUAL_PRINCIPAL', 'EQUAL_INSTALLMENT', 'INTEREST_ONLY', 'BULLET', 'CUSTOM_SCHEDULE', name='repaymentmethod'), nullable=False),
    sa.Column('next_repayment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'EXPIRED', 'MATURED', 'RENEWAL_PENDING', 'RENEWED', 'CLOSED', 'CANCELLED', name='facilitystatus'), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('security_type', sa.String(length=100), nullable=True),
    sa.Column('collateral_description', sa.String(length=1000), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('refinanced_from_facility_id', sa.UUID(), nullable=True, comment='SECTION 21: links a refinancing facility back to the one it replaced.'),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['facility_type_code'], ['facility_types.code'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['refinanced_from_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_reference')
    )
    op.create_index(op.f('ix_facilities_commitment_type'), 'facilities', ['commitment_type'], unique=False)
    op.create_index(op.f('ix_facilities_facility_type_code'), 'facilities', ['facility_type_code'], unique=False)
    op.create_index(op.f('ix_facilities_legal_entity_id'), 'facilities', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_facilities_lender_id'), 'facilities', ['lender_id'], unique=False)
    op.create_index(op.f('ix_facilities_maturity_date'), 'facilities', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_facilities_status'), 'facilities', ['status'], unique=False)
    op.create_table('facility_collateral',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('collateral_type', sa.Enum('CASH_COLLATERAL', 'FIXED_DEPOSIT', 'RECEIVABLES', 'INVENTORY', 'PROPERTY', 'EQUIPMENT', 'GUARANTEE', 'OTHER', name='collateraltype'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('haircut_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('document_reference', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RELEASED', 'EXPIRED', name='collateralstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_collateral_facility_id'), 'facility_collateral', ['facility_id'], unique=False)
    op.create_table('facility_covenants',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('covenant_type', sa.Enum('MINIMUM_LIQUIDITY', 'MAXIMUM_LEVERAGE', 'DEBT_SERVICE_COVERAGE', 'INTEREST_COVERAGE', 'CURRENT_RATIO', 'MINIMUM_NET_WORTH', 'BORROWING_BASE_AVAILABILITY', 'CUSTOM', name='covenanttype'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('operator', sa.Enum('GREATER_THAN_OR_EQUAL', 'LESS_THAN_OR_EQUAL', 'GREATER_THAN', 'LESS_THAN', 'EQUAL', name='covenantoperator'), nullable=False),
    sa.Column('measurement_frequency', sa.String(length=50), nullable=True),
    sa.Column('measurement_date', sa.Date(), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('headroom', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('status', sa.Enum('COMPLIANT', 'WARNING', 'BREACH', 'WAIVED', 'CURED', 'UNKNOWN', 'DATA_REQUIRED', name='covenantstatus'), nullable=False),
    sa.Column('warning_threshold', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('breach_threshold', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('cure_period_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_covenants_facility_id'), 'facility_covenants', ['facility_id'], unique=False)
    op.create_table('facility_events',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('FACILITY_CREATED', 'FACILITY_ACTIVATED', 'DRAW_DOWN', 'REPAYMENT', 'EARLY_REPAYMENT', 'RATE_CHANGED', 'LIMIT_CHANGED', 'MATURITY_EXTENDED', 'RENEWED', 'REFINANCED', 'FEE_CHARGED', 'COVENANT_WARNING', 'COVENANT_BREACH', 'COLLATERAL_ADDED', 'COLLATERAL_RELEASED', 'FACILITY_SUSPENDED', 'FACILITY_CLOSED', 'STATUS_CHANGED', name='facilityeventtype'), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_record_type', sa.String(length=100), nullable=True),
    sa.Column('related_record_id', sa.String(length=100), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_events_event_type'), 'facility_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_facility_events_facility_id'), 'facility_events', ['facility_id'], unique=False)
    op.create_table('facility_fees',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('fee_type', sa.Enum('ARRANGEMENT', 'COMMITMENT', 'PROCESSING', 'RENEWAL', 'EARLY_REPAYMENT', 'OTHER', name='feetype'), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('calculation_basis', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DUE', 'PAID', 'WAIVED', 'CANCELLED', name='feestatus'), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_fees_facility_id'), 'facility_fees', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_fees_legal_entity_id'), 'facility_fees', ['legal_entity_id'], unique=False)
    op.create_table('facility_sub_limits',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('purpose_code', sa.String(length=50), nullable=True),
    sa.Column('limit_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('drawn_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_sub_limits_facility_id'), 'facility_sub_limits', ['facility_id'], unique=False)
    op.create_table('facility_versions',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_versions_facility_id'), 'facility_versions', ['facility_id'], unique=False)
    op.create_table('funding_actions',
    sa.Column('action_type', sa.Enum('PROPOSE_DRAWDOWN', 'PROPOSE_REPAYMENT', 'PROPOSE_REFINANCING', 'PROPOSE_RENEWAL', 'PROPOSE_LIMIT_CHANGE', name='fundingactiontype'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('proposed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'EXECUTED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='fundingactionstatus'), nullable=False),
    sa.Column('rationale', sa.String(length=2000), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('executed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_actions_action_type'), 'funding_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_funding_actions_facility_id'), 'funding_actions', ['facility_id'], unique=False)
    op.create_index(op.f('ix_funding_actions_legal_entity_id'), 'funding_actions', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_funding_actions_status'), 'funding_actions', ['status'], unique=False)
    op.create_table('facility_drawdowns',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('sub_limit_id', sa.UUID(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('drawdown_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('drawdown_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('interest_rate_applicable', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'EXECUTED', 'REJECTED', 'CANCELLED', name='drawdownstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('executed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=150), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['sub_limit_id'], ['facility_sub_limits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_drawdowns_drawdown_date'), 'facility_drawdowns', ['drawdown_date'], unique=False)
    op.create_index(op.f('ix_facility_drawdowns_facility_id'), 'facility_drawdowns', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_drawdowns_legal_entity_id'), 'facility_drawdowns', ['legal_entity_id'], unique=False)
    op.create_table('facility_repayments',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('drawdown_id', sa.UUID(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('repayment_type', sa.Enum('PRINCIPAL', 'INTEREST', 'FEE', name='repaymenttype'), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('actual_payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'DUE', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', name='repaymentstatus'), nullable=False),
    sa.Column('is_early_repayment', sa.Boolean(), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=150), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['drawdown_id'], ['facility_drawdowns.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_repayments_due_date'), 'facility_repayments', ['due_date'], unique=False)
    op.create_index(op.f('ix_facility_repayments_facility_id'), 'facility_repayments', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_repayments_legal_entity_id'), 'facility_repayments', ['legal_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_repayments_legal_entity_id'), table_name='facility_repayments')
    op.drop_index(op.f('ix_facility_repayments_facility_id'), table_name='facility_repayments')
    op.drop_index(op.f('ix_facility_repayments_due_date'), table_name='facility_repayments')
    op.drop_table('facility_repayments')
    op.drop_index(op.f('ix_facility_drawdowns_legal_entity_id'), table_name='facility_drawdowns')
    op.drop_index(op.f('ix_facility_drawdowns_facility_id'), table_name='facility_drawdowns')
    op.drop_index(op.f('ix_facility_drawdowns_drawdown_date'), table_name='facility_drawdowns')
    op.drop_table('facility_drawdowns')
    op.drop_index(op.f('ix_funding_actions_status'), table_name='funding_actions')
    op.drop_index(op.f('ix_funding_actions_legal_entity_id'), table_name='funding_actions')
    op.drop_index(op.f('ix_funding_actions_facility_id'), table_name='funding_actions')
    op.drop_index(op.f('ix_funding_actions_action_type'), table_name='funding_actions')
    op.drop_table('funding_actions')
    op.drop_index(op.f('ix_facility_versions_facility_id'), table_name='facility_versions')
    op.drop_table('facility_versions')
    op.drop_index(op.f('ix_facility_sub_limits_facility_id'), table_name='facility_sub_limits')
    op.drop_table('facility_sub_limits')
    op.drop_index(op.f('ix_facility_fees_legal_entity_id'), table_name='facility_fees')
    op.drop_index(op.f('ix_facility_fees_facility_id'), table_name='facility_fees')
    op.drop_table('facility_fees')
    op.drop_index(op.f('ix_facility_events_facility_id'), table_name='facility_events')
    op.drop_index(op.f('ix_facility_events_event_type'), table_name='facility_events')
    op.drop_table('facility_events')
    op.drop_index(op.f('ix_facility_covenants_facility_id'), table_name='facility_covenants')
    op.drop_table('facility_covenants')
    op.drop_index(op.f('ix_facility_collateral_facility_id'), table_name='facility_collateral')
    op.drop_table('facility_collateral')
    op.drop_index(op.f('ix_facilities_status'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_maturity_date'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_lender_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_legal_entity_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_type_code'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_commitment_type'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_table('facility_types')
    # ### end Alembic commands ###
