"""fix reconciliation timestamp columns to be timezone aware

Revision ID: baa2eceadc5a
Revises: 0e4526e93f67
Create Date: 2026-09-24 16:28:06.180370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'baa2eceadc5a'
down_revision: Union[str, None] = '0e4526e93f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: autogenerate proposed dropping/recreating several hand-written
    # partial unique indexes from Stage 3/4/5A - those lines were removed
    # deliberately; none of them are touched by this migration.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reconciliation_open_items', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('reconciliation_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('reconciliation_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.alter_column('reconciliation_runs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reconciliation_runs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reconciliation_open_items', 'resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index('ux_investment_transactions_one_placement', 'investment_transactions', ['investment_id'], unique=True, postgresql_where="(transaction_type = 'PLACEMENT'::investmenttransactiontype)")
    op.create_index('ux_investment_transactions_idempotency_key', 'investment_transactions', ['investment_id', 'idempotency_key'], unique=True, postgresql_where='(idempotency_key IS NOT NULL)')
    op.create_index('ux_investment_events_rebooking_idempotency_key', 'investment_events', ['investment_id', 'reference'], unique=True, postgresql_where="((event_type = 'REBOOKED'::investmenteventtype) AND (reference IS NOT NULL))")
    op.create_index('ux_funding_actions_linked_repayment_id', 'funding_actions', ['linked_repayment_id'], unique=True, postgresql_where='(linked_repayment_id IS NOT NULL)')
    op.create_index('ux_funding_actions_linked_drawdown_id', 'funding_actions', ['linked_drawdown_id'], unique=True, postgresql_where='(linked_drawdown_id IS NOT NULL)')
    op.create_index('ux_bank_statement_transactions_strong_duplicate_key', 'bank_statement_transactions', ['duplicate_key'], unique=True, postgresql_where='(has_strong_identity = true)')
    # ### end Alembic commands ###
