"""stage5d advanced matching groups

Revision ID: c08d1cbdad93
Revises: dedd5597cddc
Create Date: 2026-10-02 13:09:42.193897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c08d1cbdad93'
down_revision: Union[str, None] = 'dedd5597cddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_match_groups',
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('ONE_TO_MANY', 'MANY_TO_ONE', 'BATCH', 'INTERNAL_TRANSFER', 'FX_MATCH', name='matchrelationshiptype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AMBIGUOUS', 'ACCEPTED', 'REJECTED', name='matchgroupstatus'), nullable=False),
    sa.Column('bank_aggregate_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('ledger_aggregate_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('difference', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fx_source_currency_code', sa.String(length=3), nullable=True),
    sa.Column('fx_target_currency_code', sa.String(length=3), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('fx_rate_date', sa.Date(), nullable=True),
    sa.Column('fx_rate_id', sa.UUID(), nullable=True),
    sa.Column('fx_rate_type', sa.String(length=20), nullable=True),
    sa.Column('fx_rate_source', sa.String(length=100), nullable=True),
    sa.Column('fx_tolerance_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('matching_rule_version', sa.String(length=50), nullable=False),
    sa.Column('group_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fx_rate_id'], ['fx_rates.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id', 'group_key', name='uq_reconciliation_match_group_identity')
    )
    op.create_index(op.f('ix_reconciliation_match_groups_reconciliation_run_id'), 'reconciliation_match_groups', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_groups_relationship_type'), 'reconciliation_match_groups', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_groups_status'), 'reconciliation_match_groups', ['status'], unique=False)
    op.create_table('reconciliation_match_group_members',
    sa.Column('match_group_id', sa.UUID(), nullable=False),
    sa.Column('bank_statement_transaction_id', sa.UUID(), nullable=True),
    sa.Column('treasury_transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(bank_statement_transaction_id IS NOT NULL)::int + (treasury_transaction_id IS NOT NULL)::int = 1', name='ck_reconciliation_match_group_member_exactly_one_side'),
    sa.ForeignKeyConstraint(['bank_statement_transaction_id'], ['bank_statement_transactions.id'], ),
    sa.ForeignKeyConstraint(['match_group_id'], ['reconciliation_match_groups.id'], ),
    sa.ForeignKeyConstraint(['treasury_transaction_id'], ['treasury_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_match_group_members_bank_statement_transaction_id'), 'reconciliation_match_group_members', ['bank_statement_transaction_id'], unique=False)
    # NOTE: several hand-written partial unique indexes from Stage
    # 3/4/5A/5C were proposed for drop/recreate by autogenerate (it
    # does not reflect postgresql_where-qualified indexes correctly)
    # - those lines were removed deliberately; none of them are
    # touched by this migration.
    op.create_index(op.f('ix_reconciliation_match_group_members_match_group_id'), 'reconciliation_match_group_members', ['match_group_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_group_members_treasury_transaction_id'), 'reconciliation_match_group_members', ['treasury_transaction_id'], unique=False)
    op.add_column('reconciliation_runs', sa.Column('advanced_match_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reconciliation_runs', sa.Column('ambiguous_advanced_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_runs', 'ambiguous_advanced_count')
    op.drop_column('reconciliation_runs', 'advanced_match_count')
    op.drop_index(op.f('ix_reconciliation_match_group_members_treasury_transaction_id'), table_name='reconciliation_match_group_members')
    op.drop_index(op.f('ix_reconciliation_match_group_members_match_group_id'), table_name='reconciliation_match_group_members')
    op.drop_index(op.f('ix_reconciliation_match_group_members_bank_statement_transaction_id'), table_name='reconciliation_match_group_members')
    op.drop_table('reconciliation_match_group_members')
    op.drop_index(op.f('ix_reconciliation_match_groups_status'), table_name='reconciliation_match_groups')
    op.drop_index(op.f('ix_reconciliation_match_groups_relationship_type'), table_name='reconciliation_match_groups')
    op.drop_index(op.f('ix_reconciliation_match_groups_reconciliation_run_id'), table_name='reconciliation_match_groups')
    op.drop_table('reconciliation_match_groups')
    # ### end Alembic commands ###
