"""add funding action linked drawdown and repayment fk

Revision ID: c56185410e6b
Revises: b12c99fb6682
Create Date: 2026-09-18 15:41:59.291793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c56185410e6b'
down_revision: Union[str, None] = 'b12c99fb6682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funding_actions', sa.Column('linked_drawdown_id', sa.UUID(), nullable=True))
    op.add_column('funding_actions', sa.Column('linked_repayment_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_funding_actions_linked_drawdown_id'), 'funding_actions', ['linked_drawdown_id'], unique=False)
    op.create_index(op.f('ix_funding_actions_linked_repayment_id'), 'funding_actions', ['linked_repayment_id'], unique=False)
    op.create_foreign_key(None, 'funding_actions', 'facility_repayments', ['linked_repayment_id'], ['id'])
    op.create_foreign_key(None, 'funding_actions', 'facility_drawdowns', ['linked_drawdown_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funding_actions', type_='foreignkey')
    op.drop_constraint(None, 'funding_actions', type_='foreignkey')
    op.drop_index(op.f('ix_funding_actions_linked_repayment_id'), table_name='funding_actions')
    op.drop_index(op.f('ix_funding_actions_linked_drawdown_id'), table_name='funding_actions')
    op.drop_column('funding_actions', 'linked_repayment_id')
    op.drop_column('funding_actions', 'linked_drawdown_id')
    # ### end Alembic commands ###
