"""add investment transaction idempotency key

Revision ID: c68cb5de2aea
Revises: 146d9a612050
Create Date: 2026-09-22 12:49:41.844669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c68cb5de2aea'
down_revision: Union[str, None] = '146d9a612050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: autogenerate proposed dropping/recreating hand-written partial
    # unique indexes it doesn't reflect in SQLAlchemy model metadata
    # (ux_funding_actions_linked_drawdown_id/linked_repayment_id from
    # Stage 3, and ux_investment_transactions_one_placement from the
    # prior Stage 4 pass) - those lines are removed deliberately; none of
    # those three indexes are touched by this migration.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_transactions', sa.Column('idempotency_key', sa.String(length=150), nullable=True, comment='SECTION 5 (Stage 4 final financial-integrity patch): a client-supplied request identity, consistent with the Stage 3 idempotency pattern of backing an application-level check with a database constraint. A retried rebooking request carrying the same key against the same investment is detected via ux_investment_transactions_idempotency_key and returns the already-applied result rather than creating a second cash movement.'))
    # ### end Alembic commands ###

    # SECTION 5: defense in depth (same pattern as the Stage 3
    # funding_actions partial unique indexes, and the prior Stage 4
    # placement-idempotency index) - a given investment may have at most
    # one InvestmentTransaction per supplied idempotency_key, enforced at
    # the database level, not just application-level pre-checking.
    op.execute(
        "CREATE UNIQUE INDEX ux_investment_transactions_idempotency_key "
        "ON investment_transactions (investment_id, idempotency_key) "
        "WHERE idempotency_key IS NOT NULL"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ux_investment_transactions_idempotency_key")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_transactions', 'idempotency_key')
    # ### end Alembic commands ###
