"""stage4 investments and fixed deposit management

Revision ID: c6a51871be60
Revises: 84d4f574d592
Create Date: 2026-09-21 09:38:36.218051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c6a51871be60'
down_revision: Union[str, None] = '84d4f574d592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: autogenerate proposed dropping/recreating
    # ux_funding_actions_linked_drawdown_id / ux_funding_actions_linked_repayment_id
    # here - those are Stage 3 hand-written partial unique indexes that
    # SQLAlchemy's model metadata doesn't reflect, so autogenerate treats
    # them as "removed" relative to the model. Those lines were removed
    # from this migration deliberately; the indexes are untouched.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_implemented', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('investment_concentration_limits',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('legal_entity_id', sa.UUID(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('investment_type_code', sa.String(length=50), nullable=True),
    sa.Column('limit_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('limit_currency_code', sa.String(length=3), nullable=False),
    sa.Column('warning_threshold_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_concentration_limits_group_id'), 'investment_concentration_limits', ['group_id'], unique=False)
    op.create_index(op.f('ix_investment_concentration_limits_institution_id'), 'investment_concentration_limits', ['institution_id'], unique=False)
    op.create_index(op.f('ix_investment_concentration_limits_legal_entity_id'), 'investment_concentration_limits', ['legal_entity_id'], unique=False)
    op.create_table('investments',
    sa.Column('investment_reference', sa.String(length=100), nullable=False),
    sa.Column('investment_type_code', sa.String(length=50), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('source_account_id', sa.UUID(), nullable=True),
    sa.Column('destination_account_id', sa.UUID(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('original_principal_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('placement_date', sa.Date(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('tenor_days', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('rate_type', sa.Enum('FIXED', 'VARIABLE', 'NEGOTIATED', 'CUSTOM', name='investmentratetype'), nullable=False),
    sa.Column('rate_source', sa.String(length=200), nullable=True),
    sa.Column('day_count_convention', sa.Enum('ACT_365', 'ACT_360', 'THIRTY_360', name='investment_day_count_convention'), nullable=False),
    sa.Column('interest_payment_method', sa.Enum('AT_MATURITY', 'PERIODIC', 'UPFRONT', name='interestpaymentmethod'), nullable=False),
    sa.Column('interest_payment_frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', 'CUSTOM', name='interestpaymentfrequency'), nullable=True),
    sa.Column('expected_interest', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('accrued_interest', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('received_interest', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('early_termination_allowed', sa.Boolean(), nullable=False),
    sa.Column('partial_termination_allowed', sa.Boolean(), nullable=False),
    sa.Column('rollover_allowed', sa.Boolean(), nullable=False),
    sa.Column('penalty_type', sa.Enum('NONE', 'RATE_REDUCTION', 'FLAT_AMOUNT', 'FORFEIT_INTEREST', 'CUSTOM', name='penaltytype'), nullable=False),
    sa.Column('penalty_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('penalty_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'PLACEMENT_PENDING', 'ACTIVE', 'MATURED', 'PARTIALLY_TERMINATED', 'TERMINATED', 'ROLLED_OVER', 'REBOOKED', 'CANCELLED', 'REJECTED', name='investmentstatus'), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_investment_id', sa.UUID(), nullable=True),
    sa.Column('rolled_to_investment_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('placed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['destination_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['investment_type_code'], ['investment_types.code'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['placed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['rolled_to_investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['source_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investment_reference')
    )
    op.create_index(op.f('ix_investments_institution_id'), 'investments', ['institution_id'], unique=False)
    op.create_index(op.f('ix_investments_investment_type_code'), 'investments', ['investment_type_code'], unique=False)
    op.create_index(op.f('ix_investments_legal_entity_id'), 'investments', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_investments_maturity_date'), 'investments', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_investments_status'), 'investments', ['status'], unique=False)
    op.create_table('investment_events',
    sa.Column('investment_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('INVESTMENT_CREATED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'PLACED', 'TERMS_CHANGED', 'INTEREST_ACCRUED', 'INTEREST_RECEIVED', 'PARTIAL_TERMINATION', 'FULL_TERMINATION', 'MATURED', 'ROLLOVER', 'REBOOKED', 'PENALTY_APPLIED', 'CANCELLED', 'STATUS_CHANGED', name='investmenteventtype'), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_record_type', sa.String(length=100), nullable=True),
    sa.Column('related_record_id', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_events_event_type'), 'investment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_investment_events_investment_id'), 'investment_events', ['investment_id'], unique=False)
    op.create_table('investment_transactions',
    sa.Column('investment_id', sa.UUID(), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('PLACEMENT', 'INTEREST_ACCRUAL', 'INTEREST_RECEIPT', 'PARTIAL_TERMINATION', 'FULL_TERMINATION', 'ROLLOVER', 'REBOOKING', 'PENALTY', 'MATURITY_SETTLEMENT', name='investmenttransactiontype'), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'EXECUTED', 'REJECTED', 'CANCELLED', name='investmenttransactionstatus'), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('related_investment_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('executed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=150), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['related_investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_transactions_investment_id'), 'investment_transactions', ['investment_id'], unique=False)
    op.create_index(op.f('ix_investment_transactions_legal_entity_id'), 'investment_transactions', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_investment_transactions_transaction_date'), 'investment_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_investment_transactions_transaction_type'), 'investment_transactions', ['transaction_type'], unique=False)
    op.create_table('investment_versions',
    sa.Column('investment_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_versions_investment_id'), 'investment_versions', ['investment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_versions_investment_id'), table_name='investment_versions')
    op.drop_table('investment_versions')
    op.drop_index(op.f('ix_investment_transactions_transaction_type'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_transaction_date'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_legal_entity_id'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_investment_id'), table_name='investment_transactions')
    op.drop_table('investment_transactions')
    op.drop_index(op.f('ix_investment_events_investment_id'), table_name='investment_events')
    op.drop_index(op.f('ix_investment_events_event_type'), table_name='investment_events')
    op.drop_table('investment_events')
    op.drop_index(op.f('ix_investments_status'), table_name='investments')
    op.drop_index(op.f('ix_investments_maturity_date'), table_name='investments')
    op.drop_index(op.f('ix_investments_legal_entity_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_investment_type_code'), table_name='investments')
    op.drop_index(op.f('ix_investments_institution_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_investment_concentration_limits_legal_entity_id'), table_name='investment_concentration_limits')
    op.drop_index(op.f('ix_investment_concentration_limits_institution_id'), table_name='investment_concentration_limits')
    op.drop_index(op.f('ix_investment_concentration_limits_group_id'), table_name='investment_concentration_limits')
    op.drop_table('investment_concentration_limits')
    op.drop_table('investment_types')
    # ### end Alembic commands ###
