"""foundation schema

Revision ID: dd8835677f6f
Revises: 
Create Date: 2026-09-15 16:41:36.651254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dd8835677f6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('is_base_currency', sa.Boolean(), nullable=False, comment='Flag for currencies usable as a Group reporting currency'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False, comment='System roles (e.g. Treasury Manager) are seeded, not user-created'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('legal_entity_id', sa.UUID(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('approval_reference', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_legal_entity_id'), 'audit_events', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_module'), 'audit_events', ['module'], unique=False)
    op.create_index(op.f('ix_audit_events_record_id'), 'audit_events', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('fx_rates',
    sa.Column('from_currency_code', sa.String(length=3), nullable=False),
    sa.Column('to_currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate_type', sa.Enum('SPOT', 'BUDGET', 'MANAGEMENT', 'TREASURY', 'HISTORICAL', name='fxratetype'), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('rate_source', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='True only for the latest version of this rate identity'),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['fx_rates.id'], ),
    sa.ForeignKeyConstraint(['to_currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency_code', 'to_currency_code', 'rate_type', 'rate_date', 'version', name='uq_fx_rate_identity')
    )
    op.create_table('groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('reporting_currency_code', sa.String(length=3), nullable=False, comment='Group-level consolidation/reporting currency'),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporting_currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.Enum('GROUP_ENTITY', 'BANKS_ACCOUNTS', 'CASH_LIQUIDITY', 'FORECAST_13WK', 'FACILITIES', 'PAYMENTS', 'BANK_RECONCILIATION', 'INTERCOMPANY_RECONCILIATION', 'WORKING_CAPITAL', 'INVESTMENTS', 'RISK_CONTROLS', 'KPIS', 'REPORTS', 'TASKS_WORKFLOW', 'ADMINISTRATION', 'EXCEL_DATA_HUB', 'CURRENCY_FX', 'AI_COPILOT', 'AUDIT', name='treasurymodule'), nullable=False),
    sa.Column('action', sa.Enum('VIEW', 'UPLOAD', 'IMPORT', 'CREATE', 'EDIT', 'SUBMIT', 'INVESTIGATE', 'ASSIGN', 'COMMENT', 'APPROVE', 'EXECUTE', 'RESOLVE', 'CLOSE', 'ADJUST', 'EXPORT', 'CONFIGURE', name='treasuryaction'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module', 'action', name='uq_role_module_action')
    )
    op.create_index(op.f('ix_permissions_role_id'), 'permissions', ['role_id'], unique=False)
    op.create_table('legal_entities',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True, comment='ISO 3166-1 alpha-2'),
    sa.Column('functional_currency_code', sa.String(length=3), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['functional_currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_legal_entities_group_id'), 'legal_entities', ['group_id'], unique=False)
    op.create_table('business_units',
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_units_legal_entity_id'), 'business_units', ['legal_entity_id'], unique=False)
    op.create_table('user_role_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.Enum('GROUP_WIDE', 'ENTITY', name='entityscopetype'), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_assignments_group_id'), 'user_role_assignments', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_legal_entity_id'), 'user_role_assignments', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_role_id'), 'user_role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_user_id'), 'user_role_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_assignments_user_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_role_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_legal_entity_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_group_id'), table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    op.drop_index(op.f('ix_business_units_legal_entity_id'), table_name='business_units')
    op.drop_table('business_units')
    op.drop_index(op.f('ix_legal_entities_group_id'), table_name='legal_entities')
    op.drop_table('legal_entities')
    op.drop_index(op.f('ix_permissions_role_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('groups')
    op.drop_table('fx_rates')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_record_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_module'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_legal_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('currencies')
    # ### end Alembic commands ###
