"""stage5c reconciliation run execution summary counts

Revision ID: dedd5597cddc
Revises: 3f41c4e2dec4
Create Date: 2026-09-25 10:32:40.636520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dedd5597cddc'
down_revision: Union[str, None] = '3f41c4e2dec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='0' ensures this is safe against an existing,
    # non-empty reconciliation_runs table (any pre-existing rows get 0,
    # matching "no execution has populated these yet").
    op.add_column('reconciliation_runs', sa.Column('candidate_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reconciliation_runs', sa.Column('suggestion_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reconciliation_runs', sa.Column('matched_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reconciliation_runs', sa.Column('ambiguous_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reconciliation_runs', sa.Column('unmatched_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reconciliation_runs', sa.Column('matching_rule_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_runs', 'matching_rule_version')
    op.drop_column('reconciliation_runs', 'unmatched_count')
    op.drop_column('reconciliation_runs', 'ambiguous_count')
    op.drop_column('reconciliation_runs', 'matched_count')
    op.drop_column('reconciliation_runs', 'suggestion_count')
    op.drop_column('reconciliation_runs', 'candidate_count')
    # ### end Alembic commands ###
