"""stage2 treasury data foundation and excel data hub

Revision ID: deecbd548d58
Revises: dd8835677f6f
Create Date: 2026-09-15 17:46:13.981129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'deecbd548d58'
down_revision: Union[str, None] = 'dd8835677f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('banks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('swift_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_event_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_direction', sa.Enum('INFLOW', 'OUTFLOW', 'TRANSFER', 'NON_CASH', name='cashdirection'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('excel_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('required_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optional_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excel_templates_code'), 'excel_templates', ['code'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('account_type_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DORMANT', 'CLOSED', name='bankaccountstatus'), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('minimum_operating_balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('overdraft_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gl_reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_type_code'], ['account_types.code'], ),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'account_number', name='uq_bank_account_number')
    )
    op.create_index(op.f('ix_bank_accounts_bank_id'), 'bank_accounts', ['bank_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_legal_entity_id'), 'bank_accounts', ['legal_entity_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'VALIDATING', 'VALIDATED', 'READY_FOR_IMPORT', 'IMPORTING', 'IMPORTED', 'PARTIALLY_IMPORTED', 'FAILED', 'CANCELLED', name='importbatchstatus'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('warning_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('raw_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_legal_entity_id'), 'import_batches', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_index(op.f('ix_import_batches_template_code'), 'import_batches', ['template_code'], unique=False)
    op.create_table('bank_balances',
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('balance_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ledger_balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id', 'balance_date', 'source', name='uq_bank_balance_identity')
    )
    op.create_index(op.f('ix_bank_balances_balance_date'), 'bank_balances', ['balance_date'], unique=False)
    op.create_index(op.f('ix_bank_balances_bank_account_id'), 'bank_balances', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_balances_import_batch_id'), 'bank_balances', ['import_batch_id'], unique=False)
    op.create_table('bank_charges',
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('charge_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('charge_type', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_charges_bank_account_id'), 'bank_charges', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_charges_import_batch_id'), 'bank_charges', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_bank_charges_legal_entity_id'), 'bank_charges', ['legal_entity_id'], unique=False)
    op.create_table('expected_collections',
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', 'OVERDUE', name='forecastitemstatus'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expected_collections_expected_date'), 'expected_collections', ['expected_date'], unique=False)
    op.create_index(op.f('ix_expected_collections_import_batch_id'), 'expected_collections', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_expected_collections_legal_entity_id'), 'expected_collections', ['legal_entity_id'], unique=False)
    op.create_table('expected_payments',
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', 'OVERDUE', name='forecastitemstatus'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expected_payments_expected_date'), 'expected_payments', ['expected_date'], unique=False)
    op.create_index(op.f('ix_expected_payments_import_batch_id'), 'expected_payments', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_expected_payments_legal_entity_id'), 'expected_payments', ['legal_entity_id'], unique=False)
    op.create_table('import_issues',
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.Enum('ERROR', 'WARNING', name='issueseverity'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_issues_import_batch_id'), 'import_issues', ['import_batch_id'], unique=False)
    op.create_table('treasury_transactions',
    sa.Column('legal_entity_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('event_type_code', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.Enum('INFLOW', 'OUTFLOW', 'TRANSFER', 'NON_CASH', name='cashdirection'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('transaction_currency_code', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('functional_currency_code', sa.String(length=3), nullable=True),
    sa.Column('functional_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('reporting_currency_code', sa.String(length=3), nullable=True),
    sa.Column('reporting_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('exchange_rate_type', sa.String(length=20), nullable=True),
    sa.Column('exchange_rate_date', sa.Date(), nullable=True),
    sa.Column('exchange_rate_source', sa.String(length=100), nullable=True),
    sa.Column('bank_id', sa.UUID(), nullable=True),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('transfer_pair_id', sa.UUID(), nullable=True),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('external_reference', sa.String(length=150), nullable=True),
    sa.Column('narration', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_type_code'], ['cash_event_types.code'], ),
    sa.ForeignKeyConstraint(['functional_currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['reporting_currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['transaction_currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treasury_transactions_bank_account_id'), 'treasury_transactions', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_treasury_transactions_direction'), 'treasury_transactions', ['direction'], unique=False)
    op.create_index(op.f('ix_treasury_transactions_event_date'), 'treasury_transactions', ['event_date'], unique=False)
    op.create_index(op.f('ix_treasury_transactions_event_type_code'), 'treasury_transactions', ['event_type_code'], unique=False)
    op.create_index(op.f('ix_treasury_transactions_import_batch_id'), 'treasury_transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_treasury_transactions_legal_entity_id'), 'treasury_transactions', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_treasury_transactions_transfer_pair_id'), 'treasury_transactions', ['transfer_pair_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treasury_transactions_transfer_pair_id'), table_name='treasury_transactions')
    op.drop_index(op.f('ix_treasury_transactions_legal_entity_id'), table_name='treasury_transactions')
    op.drop_index(op.f('ix_treasury_transactions_import_batch_id'), table_name='treasury_transactions')
    op.drop_index(op.f('ix_treasury_transactions_event_type_code'), table_name='treasury_transactions')
    op.drop_index(op.f('ix_treasury_transactions_event_date'), table_name='treasury_transactions')
    op.drop_index(op.f('ix_treasury_transactions_direction'), table_name='treasury_transactions')
    op.drop_index(op.f('ix_treasury_transactions_bank_account_id'), table_name='treasury_transactions')
    op.drop_table('treasury_transactions')
    op.drop_index(op.f('ix_import_issues_import_batch_id'), table_name='import_issues')
    op.drop_table('import_issues')
    op.drop_index(op.f('ix_expected_payments_legal_entity_id'), table_name='expected_payments')
    op.drop_index(op.f('ix_expected_payments_import_batch_id'), table_name='expected_payments')
    op.drop_index(op.f('ix_expected_payments_expected_date'), table_name='expected_payments')
    op.drop_table('expected_payments')
    op.drop_index(op.f('ix_expected_collections_legal_entity_id'), table_name='expected_collections')
    op.drop_index(op.f('ix_expected_collections_import_batch_id'), table_name='expected_collections')
    op.drop_index(op.f('ix_expected_collections_expected_date'), table_name='expected_collections')
    op.drop_table('expected_collections')
    op.drop_index(op.f('ix_bank_charges_legal_entity_id'), table_name='bank_charges')
    op.drop_index(op.f('ix_bank_charges_import_batch_id'), table_name='bank_charges')
    op.drop_index(op.f('ix_bank_charges_bank_account_id'), table_name='bank_charges')
    op.drop_table('bank_charges')
    op.drop_index(op.f('ix_bank_balances_import_batch_id'), table_name='bank_balances')
    op.drop_index(op.f('ix_bank_balances_bank_account_id'), table_name='bank_balances')
    op.drop_index(op.f('ix_bank_balances_balance_date'), table_name='bank_balances')
    op.drop_table('bank_balances')
    op.drop_index(op.f('ix_import_batches_template_code'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_legal_entity_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_bank_accounts_legal_entity_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_bank_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_excel_templates_code'), table_name='excel_templates')
    op.drop_table('excel_templates')
    op.drop_table('cash_event_types')
    op.drop_table('banks')
    op.drop_table('account_types')
    # ### end Alembic commands ###
